name: example
description: Demo of PrettyDiffText
publish_to: 'none'

environment:
  sdk: ">=3.2.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pretty_diff_text:
    path: ../
  diff_match_patch: ^0.4.1
  